<?php

namespace ActiviteBundle\Repository;

/**
 * ActiviteRealiseeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActiviteRealiseeRepository extends \Doctrine\ORM\EntityRepository
{
}
