<?php

namespace ActiviteBundle\Repository;

/**
 * ActiviteFixeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActiviteFixeeRepository extends \Doctrine\ORM\EntityRepository
{
}
