<?php

namespace ActiviteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ActiviteObligatoireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActiviteObligatoireRepository extends EntityRepository
{
}
