<?php

namespace ActiviteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TypeActiviteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeActiviteRepository extends EntityRepository
{
}
