 #---------------FENETRE HORAIRE-----------------------------
RessourceBundle_FenetreHoraire_index:
    path:     fenetreHoraire/index
    defaults: { _controller: RessourceBundle:FenetreHoraire:index }

RessourceBundle_FenetreHoraire_edit:
    path:     fenetreHoraire/edit/{id}.{pageRequete}
    defaults: { _controller: RessourceBundle:FenetreHoraire:edit, id : null, pageRequete : null }

RessourceBundle_FenetreHoraire_delete:
    path:     fenetreHoraire/delete/{id}
    defaults: { _controller: RessourceBundle:FenetreHoraire:delete }

RessourceBundle_FenetreHoraire_show:
    path:     fenetreHoraire/show/{id}
    defaults: { _controller: RessourceBundle:FenetreHoraire:show }

#---------------RESSOURCE-----------------------------
RessourceBundle_Ressource_index:
    path:     ressource/index
    defaults: { _controller: RessourceBundle:Ressource:index }

RessourceBundle_Ressource_edit:
    path:     ressource/edit/{id}
    defaults: { _controller: RessourceBundle:Ressource:edit, id : null }

RessourceBundle_Ressource_delete:
    path:     ressource/delete/{id}
    defaults: { _controller: RessourceBundle:Ressource:delete }

RessourceBundle_Ressource_show:
    path:     ressource/show/{id}
    defaults: { _controller: RessourceBundle:Ressource:show }

#---------------BESOIN TYPE RESSOURCE-----------------------------
RessourceBundle_BesoinTypeRessource_edit:
    path:     besoinTypeRessource/edit/{id}.{idActivite}
    defaults: { _controller: RessourceBundle:BesoinTypeRessource:edit, id : null  }

RessourceBundle_BesoinTypeRessource_index:
    path:     besoinTypeRessource
    defaults: { _controller: RessourceBundle:BesoinTypeRessource:index }

RessourceBundle_BesoinTypeRessource_show:
    path:     besoinTypeRessource/show/{id}
    defaults: { _controller: RessourceBundle:BesoinTypeRessource:show }

RessourceBundle_BesoinTypeRessource_delete:
    path:     besoinTypeRessource/delete/{id}
    defaults: { _controller: RessourceBundle:BesoinTypeRessource:delete }

#---------------TYPE RESSOURCE-----------------------------
RessourceBundle_TypeRessource_edit:
    path:     typeRessource/edit/{id}/{nomTypeRessource}
    defaults: { _controller: RessourceBundle:TypeRessource:edit, id : null, nomTypeRessource : null   }

RessourceBundle_TypeRessource_delete:
    path:     typeRessource/delete/{id}
    defaults: { _controller: RessourceBundle:TypeRessource:delete }

RessourceBundle_TypeRessource_index:
    path:     typeRessource
    defaults: { _controller: RessourceBundle:TypeRessource:index }

RessourceBundle_TypeRessource_show:
    path:     typeRessource/show/{id}
    defaults: { _controller: RessourceBundle:TypeRessource:show, id : null }

#---------------ENFANT----------------------------
RessourceBundle_Enfant_edit:
    path:     enfant/edit/{id}
    defaults: { _controller: RessourceBundle:Enfant:edit, id : null   }

RessourceBundle_Enfant_show:
    path:     /enfant/show/{id}
    defaults: { _controller: RessourceBundle:Enfant:show }

RessourceBundle_Enfant_delete:
    path:     enfant/delete/{id}
    defaults: { _controller: RessourceBundle:Enfant:delete }

RessourceBundle_Enfant_index:
    path:     enfant
    defaults: { _controller: RessourceBundle:Enfant:index }

#---------------GROUPE-----------------------------
RessourceBundle_Groupe_index:
    path:     groupe
    defaults: { _controller: RessourceBundle:Groupe:index }

RessourceBundle_Groupe_edit:
    path:     groupe/edit/{id}/{nomGroupe}
    defaults: { _controller: RessourceBundle:Groupe:edit, id : null, nomGroupe : null }

RessourceBundle_Groupe_show:
    path:     groupe/show/{id}
    defaults: { _controller: RessourceBundle:Groupe:show, id : null }

RessourceBundle_Groupe_delete:
    path:     groupe/delete/{id}
    defaults: { _controller: RessourceBundle:Groupe:delete }
