
RessourceBunde_FenetreHoraire_index:
    path:     FenetreHoraire/index
    defaults: { _controller: RessourceBundle:FenetreHoraire:index }

RessourceBunde_FenetreHoraire_edit:
    path:     FenetreHoraire/edit/{id}
    defaults: { _controller: RessourceBundle:FenetreHoraire:edit, id : null }

RessourceBunde_FenetreHoraire_delete:
    path:     FenetreHoraire/delete/{id}
    defaults: { _controller: RessourceBundle:FenetreHoraire:delete }

RessourceBunde_FenetreHoraire_show:
    path:     FenetreHoraire/show/{id}
    defaults: { _controller: RessourceBundle:FenetreHoraire:show }

RessourceBunde_Ressource_index:
    path:     Ressource/index
    defaults: { _controller: RessourceBundle:Ressource:index }

RessourceBunde_Ressource_edit:
    path:     Ressource/edit/{id}
    defaults: { _controller: RessourceBundle:Ressource:edit, id : null }

RessourceBunde_Ressource_delete:
    path:     Ressource/delete/{id}
    defaults: { _controller: RessourceBundle:Ressource:delete }

RessourceBunde_Ressource_show:
    path:     Ressource/show/{id}
    defaults: { _controller: RessourceBundle:Ressource:show }

RessourceBundle_BesoinTypeRessource_edit:
    path:     besoinTypeRessource/edit/{id}
    defaults: { _controller: RessourceBundle:BesoinTypeRessourceController:edit, id : null  }

RessourceBundle_BesoinTypeRessource_delete:
    path:     besoinTypeRessource/delete/{id}
    defaults: { _controller: RessourceBundle:BesoinTypeRessourceController:delete }

RessourceBundle_BesoinTypeRessource_index:
    path:     besoinTypeRessource
    defaults: { _controller: RessourceBundle:BesoinTypeRessourceController:index }

RessourceBundle_BesoinTypeRessource_show:
    path:     besoinTypeRessource/show/{id}
    defaults: { _controller: RessourceBundle:BesoinTypeRessourceController:show }

RessourceBundle_BesoinTypeRessource_edit:
    path:     besoinTypeRessource/edit/{id}
    defaults: { _controller: RessourceBundle:BesoinTypeRessource:edit, id : null   }

RessourceBundle_BesoinTypeRessource_delete:
    path:     besoinTypeRessource/delete/{id}
    defaults: { _controller: RessourceBundle:BesoinTypeRessource:delete }

RessourceBundle_BesoinTypeRessource_index:
    path:     besoinTypeRessource
    defaults: { _controller: RessourceBundle:BesoinTypeRessource:index }

RessourceBundle_BesoinTypeRessource_show:
    path:     besoinTypeRessource/show/{id}
    defaults: { _controller: RessourceBundle:BesoinTypeRessource:show }

RessourceBundle_TypeRessource_edit:
    path:     typeRessource/edit/{id}
    defaults: { _controller: RessourceBundle:TypeRessource:edit, id : null   }

RessourceBundle_TypeRessource_delete:
    path:     typeRessource/delete/{id}
    defaults: { _controller: RessourceBundle:TypeRessource:delete }

RessourceBundle_TypeRessource_index:
    path:     typeRessource
    defaults: { _controller: RessourceBundle:TypeRessource:index }

RessourceBundle_TypeRessource_show:
    path:     typeRessource/show/{id}
    defaults: { _controller: RessourceBundle:TypeRessource:show }

RessourceBundle_Enfant_edit:
    path:     enfant/edit/{id}
    defaults: { _controller: RessourceBundle:Enfant:edit, id : null   }

RessourceBundle_Enfant_show:
    path:     enfant/show/{id}
    defaults: { _controller: RessourceBundle:Enfant:show }

RessourceBundle_Enfant_delete:
    path:     enfant/delete/{id}
    defaults: { _controller: RessourceBundle:Enfant:delete }

RessourceBundle_Enfant_index:
    path:     enfant
    defaults: { _controller: RessourceBundle:Enfant:index }

RessourceBundle_AffectationRessource_index:
    path:     affectationRessource/index/{id}
    defaults: { _controller: RessourceBundle:AffectationRessource:index, id : null }
