
RessourceBunde_FenetreHoraire_index:
    path:     FenetreHoraire/index
    defaults: { _controller: RessourceBundle:FenetreHoraire:index }

RessourceBunde_FenetreHoraire_edit:
    path:     FenetreHoraire/edit/{id}
    defaults: { _controller: RessourceBundle:FenetreHoraire:edit, id : null }

RessourceBunde_FenetreHoraire_delete:
    path:     FenetreHoraire/delete/{id}
    defaults: { _controller: RessourceBundle:FenetreHoraire:delete }

RessourceBunde_FenetreHoraire_show:
    path:     FenetreHoraire/show/{id}
    defaults: { _controller: RessourceBundle:FenetreHoraire:show }

RessourceBunde_Ressource_index:
    path:     Ressource/index
    defaults: { _controller: RessourceBundle:Ressource:index }

RessourceBunde_Ressource_edit:
    path:     Ressource/edit/{id}
    defaults: { _controller: RessourceBundle:Ressource:edit, id : null }

RessourceBunde_Ressource_delete:
    path:     Ressource/delete/{id}
    defaults: { _controller: RessourceBundle:Ressource:delete }

RessourceBunde_Ressource_show:
    path:     Ressource/show/{id}
    defaults: { _controller: RessourceBundle:Ressource:show }

edit:
    path:     besoinTypeRessource
    defaults: { _controller: RessourceBundle:BesoinTypeRessourceController:edit }

delete:
    path:     besoinTypeRessource
    defaults: { _controller: RessourceBundle:BesoinTypeRessourceController:delete }

index:
    path:     besoinTypeRessource
    defaults: { _controller: RessourceBundle:BesoinTypeRessourceController:index }

show:
    path:     besoinTypeRessource
    defaults: { _controller: RessourceBundle:BesoinTypeRessourceController:show }

edit:
    path:     besoinTypeRessource
    defaults: { _controller: RessourceBundle:BesoinTypeRessource:edit }

delete:
    path:     besoinTypeRessource
    defaults: { _controller: RessourceBundle:BesoinTypeRessource:delete }

index:
    path:     besoinTypeRessource
    defaults: { _controller: RessourceBundle:BesoinTypeRessource:index }

show:
    path:     besoinTypeRessource
    defaults: { _controller: RessourceBundle:BesoinTypeRessource:show }

edit:
    path:     typeRessource
    defaults: { _controller: RessourceBundle:TypeRessource:edit }

delete:
    path:     typeRessource
    defaults: { _controller: RessourceBundle:TypeRessource:delete }

index:
    path:     typeRessource
    defaults: { _controller: RessourceBundle:TypeRessource:index }

show:
    path:     typeRessource
    defaults: { _controller: RessourceBundle:TypeRessource:show }
