
RessourceBunde_FenetreHoraire_index:
    path:     FenetreHoraire/index
    defaults: { _controller: RessourceBundle:FenetreHoraire:index }

RessourceBunde_FenetreHoraire_edit:
    path:     FenetreHoraire/edit/{id}
    defaults: { _controller: RessourceBundle:FenetreHoraire:edit, id : null }

RessourceBunde_FenetreHoraire_delete:
    path:     FenetreHoraire/delete/{id}
    defaults: { _controller: RessourceBundle:FenetreHoraire:delete }

RessourceBunde_FenetreHoraire_show:
    path:     FenetreHoraire/show/{id}
    defaults: { _controller: RessourceBundle:FenetreHoraire:show }
