#---------------FENETRE HORAIRE-----------------------------
RessourceBunde_FenetreHoraire_index:
    path:     FenetreHoraire/index
    defaults: { _controller: RessourceBundle:FenetreHoraire:index }

RessourceBunde_FenetreHoraire_edit:
    path:     FenetreHoraire/edit/{id}
    defaults: { _controller: RessourceBundle:FenetreHoraire:edit, id : null }

RessourceBunde_FenetreHoraire_delete:
    path:     FenetreHoraire/delete/{id}
    defaults: { _controller: RessourceBundle:FenetreHoraire:delete }

RessourceBunde_FenetreHoraire_show:
    path:     FenetreHoraire/show/{id}
    defaults: { _controller: RessourceBundle:FenetreHoraire:show }

#---------------RESSOURCE-----------------------------
RessourceBunde_Ressource_index:
    path:     Ressource/index
    defaults: { _controller: RessourceBundle:Ressource:index }

RessourceBunde_Ressource_edit:
    path:     Ressource/edit/{id}
    defaults: { _controller: RessourceBundle:Ressource:edit, id : null }

RessourceBunde_Ressource_delete:
    path:     Ressource/delete/{id}
    defaults: { _controller: RessourceBundle:Ressource:delete }

RessourceBunde_Ressource_show:
    path:     Ressource/show/{id}
    defaults: { _controller: RessourceBundle:Ressource:show }

#---------------VEHICULE-----------------------------
RessourceBundle_Vehicule_edit:
    path:     vehicule/edit
    defaults: { _controller: RessourceBundle:Vehicule:edit }

RessourceBundle_Vehicule_delete:
    path:     vehicule/delete
    defaults: { _controller: RessourceBundle:Vehicule:delete }

RessourceBundle_Vehicule_show:
    path:     vehicule/show
    defaults: { _controller: RessourceBundle:Vehicule:show }

RessourceBundle_Vehicule_index:
    path:     vehicule/index
    defaults: { _controller: RessourceBundle:Vehicule:index }
