<?php

namespace RessourceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FenetreHoraireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FenetreHoraireRepository extends EntityRepository
{
}
