<?php

namespace RessourceBundle\Repository;

/**
 * groupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class groupeRepository extends \Doctrine\ORM\EntityRepository
{
}
