<?php

namespace RessourceBundle\Repository;

/**
 * PreaffectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PreaffectionRepository extends \Doctrine\ORM\EntityRepository
{
}
