core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /

activite:
    resource: "@ActiviteBundle/Resources/config/routing.yml"
    prefix:   /

ressource:
    resource: "@RessourceBundle/Resources/config/routing.yml"
    prefix:   /

