stats:
    resource: "@StatsBundle/Resources/config/routing.yml"
    prefix:   /

utilisateur:
    resource: "@UtilisateurBundle/Resources/config/routing.yml"
    prefix:   /
    
core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /

activite:
    resource: "@ActiviteBundle/Resources/config/routing.yml"
    prefix:   /

ressource:
    resource: "@RessourceBundle/Resources/config/routing.yml"
    prefix:   /
    
adesigns_calendar:
    resource: "@ADesignsCalendarBundle/Resources/config/routing.yml"
    prefix: /
