 #---------------TYPE ACTIVITE-----------------------------
ActiviteBundle_TypeActivite_index :
    path:     typeActivite/index
    defaults: { _controller: ActiviteBundle:TypeActivite:index }

ActiviteBundle_TypeActivite_edit:
    path:     typeActivite/edit/{id}
    defaults: { _controller: ActiviteBundle:TypeActivite:edit,id : null }

ActiviteBundle_TypeActivite_delete:
    path:     typeActivite/delete/{id}
    defaults: { _controller: ActiviteBundle:TypeActivite:delete }

ActiviteBundle_TypeActivite_show:
    path:     typeActivite/show/{id}
    defaults: { _controller: ActiviteBundle:TypeActivite:show }
    
# ---------------ACTIVITE--------------------------------------------------------
ActiviteBundle_Activite_index :
    path:     activite/index
    defaults: { _controller: ActiviteBundle:Activite:index }

ActiviteBundle_activite_edit:
    path:     activite/edit/{id}
    defaults: { _controller: ActiviteBundle:Activite:edit,id : null }

ActiviteBundle_activite_show:
    path: activite/show
    defaults: { _controller: ActiviteBundle:Activite:show}
    
ActiviteBundle_activite_delete:
    path: activite/delete/{id}
    defaults: { _controller: ActiviteBundle:Activite:delete, id : null }

#---------------ACTIVITE OBLIGATOIRE ---------------------------------------------
ActiviteBundle_activiteObligatoire_edit:
    path: activiteObligatoire/edit/{id}
    defaults: { _controller: ActiviteBundle:ActiviteObligatoire:edit,id : null }

ActiviteBundle_activiteObligatoire_show:
    path: activiteObligatoire/show
    defaults: { _controller: ActiviteBundle:ActiviteObligatoire:show }

ActiviteBundle_activiteObligatoire_delete:
    path: activiteObligatoire/delete/{id}
    defaults: { _controller: ActiviteBundle:ActiviteObligatoire:delete, id : null }

ActiviteBundle_ActiviteFixee_index:
    path:     ActiviteFixee/index
    defaults: { _controller: ActiviteBundle:ActiviteFixee:index }

 #---------------ACTIVITE FIXEE-----------------------------

ActiviteBundle_ActiviteFixee_show:
    path:     ActiviteFixee/show/{id}
    defaults: { _controller: ActiviteBundle:ActiviteFixee:show }

ActiviteBundle_ActiviteFixee_delete:
    path:     ActiviteFixee/delete/{id}
    defaults: { _controller: ActiviteBundle:ActiviteFixee:delete }

ActiviteBundle_ActiviteFixee_edit:
    path:     ActiviteFixee/edit/{id}
    defaults: { _controller: ActiviteBundle:ActiviteFixee:edit , id : null }

 #---------------Jour-----------------------------

ActiviteBundle_Jour_index:
    path:     Jour/index
    defaults: { _controller: ActiviteBundle:Jour:index }

ActiviteBundle_Jour_show:
    path:     Jour/show/{id}
    defaults: { _controller: ActiviteBundle:Jour:show }
