 #---------------TYPE ACTIVITE-----------------------------
ActiviteBundle_TypeActivite_index :
    path:     typeActivite/
    defaults: { _controller: ActiviteBundle:TypeActivite:index }

ActiviteBundle_TypeActivite_edit:
    path:     typeActivite/edit/{id}
    defaults: { _controller: ActiviteBundle:TypeActivite:edit,id : null }

ActiviteBundle_TypeActivite_delete:
    path:     typeActivite/delete/{id}
    defaults: { _controller: ActiviteBundle:TypeActivite:delete }

ActiviteBundle_TypeActivite_show:
    path:     typeActivite/show/
    defaults: { _controller: ActiviteBundle:TypeActivite:show }
    
# ---------------ACTIVITE--------------------------------------------------------
ActiviteBundle_Activite_edit:
    path:     activite/edit/{id}
    defaults: { _controller: ActiviteBundle:Activite:edit,id : null }

ActiviteBundle_Activite_show:
    path: activite/show
    defaults: { _controller: ActiviteBundle:Activite:show}
    
ActiviteBundle_Activite_delete:
    path: activite/delete/{id}
    defaults: { _controller: ActiviteBundle:Activite:delete, id : null }

#---------------ACTIVITE OBLIGATOIRE ---------------------------------------------
ActiviteBundle_ActiviteObligatoire_edit:
    path: activiteObligatoire/edit/{id}
    defaults: { _controller: ActiviteBundle:ActiviteObligatoire:edit,id : null }

ActiviteBundle_ActiviteObligatoire_show:
    path: activiteObligatoire/show
    defaults: { _controller: ActiviteBundle:ActiviteObligatoire:show }

ActiviteBundle_ActiviteObligatoire_delete:
    path: activiteObligatoire/delete/{id}
    defaults: { _controller: ActiviteBundle:ActiviteObligatoire:delete, id : null }
