 #---------------TYPE ACTIVITE-----------------------------
ActiviteBundle_TypeActivite_index :
    path:     typeActivite/
    defaults: { _controller: ActiviteBundle:TypeActivite:index }

ActiviteBundle_TypeActivite_edit:
    path:     typeActivite/edit/{id}
    defaults: { _controller: ActiviteBundle:TypeActivite:edit,id : null }

ActiviteBundle_TypeActivite_delete:
    path:     typeActivite/delete/{id}
    defaults: { _controller: ActiviteBundle:TypeActivite:delete }

ActiviteBundle_TypeActivite_show:
    path:     typeActivite/show/{id}
    defaults: { _controller: ActiviteBundle:TypeActivite:show }
    
# ---------------ACTIVITE--------------------------------------------------------
ActiviteBundle_Activite_index:
    path:     activite/
    defaults: { _controller: ActiviteBundle:Activite:index }

ActiviteBundle_Activite_edit:
    path:     activite/edit/{id}
    defaults: { _controller: ActiviteBundle:Activite:edit,id : null }

ActiviteBundle_Activite_show:
    path: activite/show/{id}
    defaults: { _controller: ActiviteBundle:Activite:show,id : null}
    
ActiviteBundle_Activite_delete:
    path: activite/delete/{id}
    defaults: { _controller: ActiviteBundle:Activite:delete, id : null }

ActiviteBundle_Activite_deletes:
    path: activite/deletes/{listActivite}
    defaults: { _controller: ActiviteBundle:Activite:deletes }
    

#---------------ACTIVITE OBLIGATOIRE ---------------------------------------------

ActiviteBundle_ActiviteObligatoire_index :
    path:     activiteObligatoire/
    defaults: { _controller: ActiviteBundle:ActiviteObligatoire:index }

ActiviteBundle_ActiviteObligatoire_edit:
    path: activiteObligatoire/edit/{id}
    defaults: { _controller: ActiviteBundle:ActiviteObligatoire:edit,id : null }

ActiviteBundle_ActiviteObligatoire_show:
    path: activiteObligatoire/show
    defaults: { _controller: ActiviteBundle:ActiviteObligatoire:show }

ActiviteBundle_ActiviteObligatoire_delete:
    path: activiteObligatoire/delete/{id}
    defaults: { _controller: ActiviteBundle:ActiviteObligatoire:delete, id : null }

 #---------------ACTIVITE FIXEE-----------------------------

ActiviteBundle_ActiviteFixee_index:
    path:     ActiviteFixee/
    defaults: { _controller: ActiviteBundle:ActiviteFixee:index }


ActiviteBundle_ActiviteFixee_show:
    path:     ActiviteFixee/show/{id}
    defaults: { _controller: ActiviteBundle:ActiviteFixee:show }

ActiviteBundle_ActiviteFixee_delete:
    path:     ActiviteFixee/delete/{id}
    defaults: { _controller: ActiviteBundle:ActiviteFixee:delete }

ActiviteBundle_ActiviteFixee_edit:
    path:     ActiviteFixee/edit/{id}
    defaults: { _controller: ActiviteBundle:ActiviteFixee:edit , id : null }

 #---------------ACTIVITE REALISEE-----------------------------

ActiviteBundle_ActiviteRealisee_index:
    path:     ActiviteRealisee/
    defaults: { _controller: ActiviteBundle:ActiviteRealisee:index }


ActiviteBundle_ActiviteRealisee_show:
    path:     ActiviteRealisee/show/{id}
    defaults: { _controller: ActiviteBundle:ActiviteRealisee:show }

ActiviteBundle_ActiviteRealisee_delete:
    path:     ActiviteRealisee/delete/{id}
    defaults: { _controller: ActiviteBundle:ActiviteRealisee:delete }

ActiviteBundle_ActiviteRealisee_edit:
    path:     ActiviteRealisee/edit/{id}
    defaults: { _controller: ActiviteBundle:ActiviteRealisee:edit , id : null }

 #---------------Jour-----------------------------

ActiviteBundle_Jour_index:
    path:     Jour/
    defaults: { _controller: ActiviteBundle:Jour:index }

ActiviteBundle_Jour_show:
    path:     Jour/show/{id}
    defaults: { _controller: ActiviteBundle:Jour:show }
