enfant_index:
    path:     /
    defaults: { _controller: "RessourceBundle:Enfant:index" }
    methods:  GET

enfant_show:
    path:     /{id}/show
    defaults: { _controller: "RessourceBundle:Enfant:show" }
    methods:  GET

enfant_new:
    path:     /new
    defaults: { _controller: "RessourceBundle:Enfant:new" }
    methods:  [GET, POST]

enfant_edit:
    path:     /{id}/edit
    defaults: { _controller: "RessourceBundle:Enfant:edit" }
    methods:  [GET, POST]

enfant_delete:
    path:     /{id}/delete
    defaults: { _controller: "RessourceBundle:Enfant:delete" }
    methods:  DELETE
