#Pages de Calendrier
Calendar:
    path:     /Calendar
    defaults: { _controller: ADesignsCalendarBundle:Calendar:index }

Calendar_enfant:
    path: /Calendar/{id}
    defaults: {_controller:  ADesignsCalendarBundle:Calendar:show }
    
    
# Fonction CRUD
Calendar_event_add:
    path: /Calendar/AddEvent/
    defaults: {_controller:  ADesignsCalendarBundle:Calendar:editEvent }
    
Calendar_event_delete:
    path: /Calendar/DeleteEvent/
    defaults: {_controller:  ADesignsCalendarBundle:Calendar:deleteEvent }
    
Calendar_event_save:
    path: /Calendar/Save/
    defaults: { _controller : ADesignsCalendarBundle:Calendar:saveActivity }
    
Calendar_event_restore:
    path: /Calendar/Restore/
    defaults: { _controller : ADesignsCalendarBundle:Calendar:restoreActivity }    
    
# Loader AJAX
# Ressources Json
Ressources_loader_:
    path: /Calendar/Ressources/
    defaults: { _controller: ADesignsCalendarBundle:Calendar:loadAllRessource }
    options:
        expose: true 

RessourcesById_loader:
    path: /Calendar/Ressources/{id}
    defaults: { _controller: ADesignsCalendarBundle:Calendar:loadRessourceById }
    options:
        expose: true

# Events Json 
Events_loader:
    path: /Calendar/Events/
    defaults: { _controller: ADesignsCalendarBundle:Calendar:loadCalendar }
    options:
        expose: true      
       
EventsById_loader :
    path: /Calendar/Events/{id}
    defaults: { _controller: ADesignsCalendarBundle:Calendar:loadCalendarById }
    options:
        expose: true

EventsByIdStatic_loader :
    path: /Calendar/EventsStatic/{id}
    defaults: { _controller: ADesignsCalendarBundle:Calendar:loadCalendarStaticById }
    options:
        expose: true
