<?php

namespace Proxies\__CG__\RessourceBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Ressource extends \RessourceBundle\Entity\Ressource implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'RessourceBundle\\Entity\\Ressource' . "\0" . 'id', '' . "\0" . 'RessourceBundle\\Entity\\Ressource' . "\0" . 'designation', '' . "\0" . 'RessourceBundle\\Entity\\Ressource' . "\0" . 'activiteesRealisees', '' . "\0" . 'RessourceBundle\\Entity\\Ressource' . "\0" . 'fenetreHoraire', '' . "\0" . 'RessourceBundle\\Entity\\Ressource' . "\0" . 'typeRessource', '' . "\0" . 'RessourceBundle\\Entity\\Ressource' . "\0" . 'preAffections'];
        }

        return ['__isInitialized__', '' . "\0" . 'RessourceBundle\\Entity\\Ressource' . "\0" . 'id', '' . "\0" . 'RessourceBundle\\Entity\\Ressource' . "\0" . 'designation', '' . "\0" . 'RessourceBundle\\Entity\\Ressource' . "\0" . 'activiteesRealisees', '' . "\0" . 'RessourceBundle\\Entity\\Ressource' . "\0" . 'fenetreHoraire', '' . "\0" . 'RessourceBundle\\Entity\\Ressource' . "\0" . 'typeRessource', '' . "\0" . 'RessourceBundle\\Entity\\Ressource' . "\0" . 'preAffections'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Ressource $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDesignation($designation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDesignation', [$designation]);

        return parent::setDesignation($designation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDesignation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDesignation', []);

        return parent::getDesignation();
    }

    /**
     * {@inheritDoc}
     */
    public function addActiviteesRealisee(\ActiviteBundle\Entity\ActiviteRealisee $activiteesRealisee)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addActiviteesRealisee', [$activiteesRealisee]);

        return parent::addActiviteesRealisee($activiteesRealisee);
    }

    /**
     * {@inheritDoc}
     */
    public function removeActiviteesRealisee(\ActiviteBundle\Entity\ActiviteRealisee $activiteesRealisee)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeActiviteesRealisee', [$activiteesRealisee]);

        return parent::removeActiviteesRealisee($activiteesRealisee);
    }

    /**
     * {@inheritDoc}
     */
    public function getActiviteesRealisees()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActiviteesRealisees', []);

        return parent::getActiviteesRealisees();
    }

    /**
     * {@inheritDoc}
     */
    public function setFenetreHoraire(\RessourceBundle\Entity\FenetreHoraire $fenetreHoraire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFenetreHoraire', [$fenetreHoraire]);

        return parent::setFenetreHoraire($fenetreHoraire);
    }

    /**
     * {@inheritDoc}
     */
    public function getFenetreHoraire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFenetreHoraire', []);

        return parent::getFenetreHoraire();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeRessource(\RessourceBundle\Entity\TypeRessource $typeRessource)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeRessource', [$typeRessource]);

        return parent::setTypeRessource($typeRessource);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeRessource()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeRessource', []);

        return parent::getTypeRessource();
    }

    /**
     * {@inheritDoc}
     */
    public function addPreaffection(\RessourceBundle\Entity\Preaffection $preaffection)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPreaffection', [$preaffection]);

        return parent::addPreaffection($preaffection);
    }

    /**
     * {@inheritDoc}
     */
    public function removePreaffection(\RessourceBundle\Entity\Preaffection $preaffection)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePreaffection', [$preaffection]);

        return parent::removePreaffection($preaffection);
    }

    /**
     * {@inheritDoc}
     */
    public function getPreaffection()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreaffection', []);

        return parent::getPreaffection();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getPreAffections()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreAffections', []);

        return parent::getPreAffections();
    }

}
