<?php

namespace Proxies\__CG__\RessourceBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class FenetreHoraire extends \RessourceBundle\Entity\FenetreHoraire implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'RessourceBundle\\Entity\\FenetreHoraire' . "\0" . 'id', '' . "\0" . 'RessourceBundle\\Entity\\FenetreHoraire' . "\0" . 'lundiDebut', '' . "\0" . 'RessourceBundle\\Entity\\FenetreHoraire' . "\0" . 'lundiFin', '' . "\0" . 'RessourceBundle\\Entity\\FenetreHoraire' . "\0" . 'mardiDebut', '' . "\0" . 'RessourceBundle\\Entity\\FenetreHoraire' . "\0" . 'mardiFin', '' . "\0" . 'RessourceBundle\\Entity\\FenetreHoraire' . "\0" . 'mercrediDebut', '' . "\0" . 'RessourceBundle\\Entity\\FenetreHoraire' . "\0" . 'mercrediFin', '' . "\0" . 'RessourceBundle\\Entity\\FenetreHoraire' . "\0" . 'jeudiDebut', '' . "\0" . 'RessourceBundle\\Entity\\FenetreHoraire' . "\0" . 'jeudiFin', '' . "\0" . 'RessourceBundle\\Entity\\FenetreHoraire' . "\0" . 'vendrediDebut', '' . "\0" . 'RessourceBundle\\Entity\\FenetreHoraire' . "\0" . 'vendrediFin', '' . "\0" . 'RessourceBundle\\Entity\\FenetreHoraire' . "\0" . 'ressources', '' . "\0" . 'RessourceBundle\\Entity\\FenetreHoraire' . "\0" . 'activites', '' . "\0" . 'RessourceBundle\\Entity\\FenetreHoraire' . "\0" . 'enfants'];
        }

        return ['__isInitialized__', '' . "\0" . 'RessourceBundle\\Entity\\FenetreHoraire' . "\0" . 'id', '' . "\0" . 'RessourceBundle\\Entity\\FenetreHoraire' . "\0" . 'lundiDebut', '' . "\0" . 'RessourceBundle\\Entity\\FenetreHoraire' . "\0" . 'lundiFin', '' . "\0" . 'RessourceBundle\\Entity\\FenetreHoraire' . "\0" . 'mardiDebut', '' . "\0" . 'RessourceBundle\\Entity\\FenetreHoraire' . "\0" . 'mardiFin', '' . "\0" . 'RessourceBundle\\Entity\\FenetreHoraire' . "\0" . 'mercrediDebut', '' . "\0" . 'RessourceBundle\\Entity\\FenetreHoraire' . "\0" . 'mercrediFin', '' . "\0" . 'RessourceBundle\\Entity\\FenetreHoraire' . "\0" . 'jeudiDebut', '' . "\0" . 'RessourceBundle\\Entity\\FenetreHoraire' . "\0" . 'jeudiFin', '' . "\0" . 'RessourceBundle\\Entity\\FenetreHoraire' . "\0" . 'vendrediDebut', '' . "\0" . 'RessourceBundle\\Entity\\FenetreHoraire' . "\0" . 'vendrediFin', '' . "\0" . 'RessourceBundle\\Entity\\FenetreHoraire' . "\0" . 'ressources', '' . "\0" . 'RessourceBundle\\Entity\\FenetreHoraire' . "\0" . 'activites', '' . "\0" . 'RessourceBundle\\Entity\\FenetreHoraire' . "\0" . 'enfants'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (FenetreHoraire $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setLundiDebut($lundiDebut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLundiDebut', [$lundiDebut]);

        return parent::setLundiDebut($lundiDebut);
    }

    /**
     * {@inheritDoc}
     */
    public function getLundiDebut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLundiDebut', []);

        return parent::getLundiDebut();
    }

    /**
     * {@inheritDoc}
     */
    public function setLundiFin($lundiFin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLundiFin', [$lundiFin]);

        return parent::setLundiFin($lundiFin);
    }

    /**
     * {@inheritDoc}
     */
    public function getLundiFin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLundiFin', []);

        return parent::getLundiFin();
    }

    /**
     * {@inheritDoc}
     */
    public function setMardiDebut($mardiDebut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMardiDebut', [$mardiDebut]);

        return parent::setMardiDebut($mardiDebut);
    }

    /**
     * {@inheritDoc}
     */
    public function getMardiDebut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMardiDebut', []);

        return parent::getMardiDebut();
    }

    /**
     * {@inheritDoc}
     */
    public function setMardiFin($mardiFin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMardiFin', [$mardiFin]);

        return parent::setMardiFin($mardiFin);
    }

    /**
     * {@inheritDoc}
     */
    public function getMardiFin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMardiFin', []);

        return parent::getMardiFin();
    }

    /**
     * {@inheritDoc}
     */
    public function setMercrediDebut($mercrediDebut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMercrediDebut', [$mercrediDebut]);

        return parent::setMercrediDebut($mercrediDebut);
    }

    /**
     * {@inheritDoc}
     */
    public function getMercrediDebut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMercrediDebut', []);

        return parent::getMercrediDebut();
    }

    /**
     * {@inheritDoc}
     */
    public function setMercrediFin($mercrediFin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMercrediFin', [$mercrediFin]);

        return parent::setMercrediFin($mercrediFin);
    }

    /**
     * {@inheritDoc}
     */
    public function getMercrediFin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMercrediFin', []);

        return parent::getMercrediFin();
    }

    /**
     * {@inheritDoc}
     */
    public function setJeudiDebut($jeudiDebut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJeudiDebut', [$jeudiDebut]);

        return parent::setJeudiDebut($jeudiDebut);
    }

    /**
     * {@inheritDoc}
     */
    public function getJeudiDebut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJeudiDebut', []);

        return parent::getJeudiDebut();
    }

    /**
     * {@inheritDoc}
     */
    public function setJeudiFin($jeudiFin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJeudiFin', [$jeudiFin]);

        return parent::setJeudiFin($jeudiFin);
    }

    /**
     * {@inheritDoc}
     */
    public function getJeudiFin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJeudiFin', []);

        return parent::getJeudiFin();
    }

    /**
     * {@inheritDoc}
     */
    public function setVendrediDebut($vendrediDebut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVendrediDebut', [$vendrediDebut]);

        return parent::setVendrediDebut($vendrediDebut);
    }

    /**
     * {@inheritDoc}
     */
    public function getVendrediDebut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVendrediDebut', []);

        return parent::getVendrediDebut();
    }

    /**
     * {@inheritDoc}
     */
    public function setVendrediFin($vendrediFin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVendrediFin', [$vendrediFin]);

        return parent::setVendrediFin($vendrediFin);
    }

    /**
     * {@inheritDoc}
     */
    public function getVendrediFin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVendrediFin', []);

        return parent::getVendrediFin();
    }

    /**
     * {@inheritDoc}
     */
    public function isValidDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isValidDate', []);

        return parent::isValidDate();
    }

    /**
     * {@inheritDoc}
     */
    public function addRessource(\RessourceBundle\Entity\Ressource $ressource)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRessource', [$ressource]);

        return parent::addRessource($ressource);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRessource(\RessourceBundle\Entity\Ressource $ressource)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRessource', [$ressource]);

        return parent::removeRessource($ressource);
    }

    /**
     * {@inheritDoc}
     */
    public function getRessources()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRessources', []);

        return parent::getRessources();
    }

    /**
     * {@inheritDoc}
     */
    public function addActivite(\ActiviteBundle\Entity\Activite $activite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addActivite', [$activite]);

        return parent::addActivite($activite);
    }

    /**
     * {@inheritDoc}
     */
    public function removeActivite(\ActiviteBundle\Entity\Activite $activite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeActivite', [$activite]);

        return parent::removeActivite($activite);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivites()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivites', []);

        return parent::getActivites();
    }

    /**
     * {@inheritDoc}
     */
    public function addEnfant(\RessourceBundle\Entity\Enfant $enfant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEnfant', [$enfant]);

        return parent::addEnfant($enfant);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEnfant(\RessourceBundle\Entity\Enfant $enfant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEnfant', [$enfant]);

        return parent::removeEnfant($enfant);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnfants()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnfants', []);

        return parent::getEnfants();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
