<?php

namespace CalendarBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * calendarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
}
