<?php

namespace CalendarBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * calendarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository {

    /**
     * //Le nombre d'enfants pour une activité
     * @param type $activite
     * @return type
     */
    function contrainteNbrEnfants($activite) {

        $query = $this->_em->createQuery("SELECT Count (event.activite) "
                . "                         FROM ADesignsCalendarBundle:EventEntity event "
                . "                         WHERE event.activite = :activite "
                . "                         GROUP BY event.activite, event.jour, event.startDatetime");
        $query->setParameter('activite', $activite);

        $result = $query->getSingleResult();


        return $result ['1'];
    }

    /**
     * Durée d'une activité 
     * @param type $activite
     * @return type
     */
    function contrainteDuree($activite) {

        $query = $this->_em->createQuery("SELECT event.endDatetime , event.startDatetime "
                . "                         FROM ADesignsCalendarBundle:EventEntity event "
                . "                         WHERE event.activite = :activite ");
        $query->setParameter('activite', $activite);

        $result = $query->getSingleResult();
        $endDatetime = $result['endDatetime'];
        $startDatetime = $result['startDatetime'];
        $diff = abs($endDatetime->getTimestamp() - $startDatetime->getTimestamp()) / 60; //durée en minutes          
        return $diff;
    }

}
